version: '2'
services:
    ussdapi-app:
        image: ussdapi
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://ussdapi-mariadb:3306/ussdapi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ussdapi-mariadb:
        extends:
            file: mariadb.yml
            service: ussdapi-mariadb
